EXP_DIR: ycb_dataset
CODE_DIM: 128
CAPACITY: 1
GPU_ID: 0
TRAIN:
  RoI_ACC: True
  TRAIN_TRANSNET: False
  TRAIN_AAE: True
  DEPTH_EMBEDDING: True
  OBJECTS: !!python/tuple ['003_cracker_box']
  BOOTSTRAP_CONST: 2000
  USE_TRIPLET_LOSS: False
  WORKERS: 0
  TRANS_SEP: False
  DEEPER_TRANSNET: True
  ONLINE_RENDERING: True
  RENDER_DIST: !!python/tuple [1.2796905]
  LIGHT_INT_MIN: 0.3
  LIGHT_INT_MAX: 3.0
  LIGHT_COLOR_VAR: 0.8
  LIGHT_R_MAX: 3.0
  LIGHT_R_MIN: 0.25
#  TRANSNET_CAPACITY: !!python/tuple [20, 40, 64]
  TRANSNET_CAPACITY: !!python/tuple [128, 256, 256]
#  TRANSNET_CAPACITY: !!python/tuple [64, 128, 256, 128]
  SHIFT_MIN: -5.0
  SHIFT_MAX: 5.0
  SCALE_MIN: 0.975
  SCALE_MAX: 1.025
  OC_PROB: 0.3
  N_OCCLUDERS: 3
  TRUNC_PROB: 0.2
  OC_XY_RANGE: !!python/tuple [-0.1, 0.1]
  OC_Z_RANGE: !!python/tuple [0, 0.2]
  TRUNC_X_MAX: 1.0
  TRUNC_Y_MAX: 1.0
  TRIPLET_LOSS_WT: 1.0
  ROI_CENTER_RANGE: [59.0, 69.0, 59.0, 69.0]
  ROI_SIZE_RANGE: [124.8, 131.2]
  USE_OCCLUSION: True