EXP_DIR: ycb_dataset
CODE_DIM: 128
GPU_ID: 1
TRAIN:
  DEPTH_EMBEDDING: True
  OBJECTS: !!python/tuple ['024_bowl']
  BOOTSTRAP_CONST: 200
  USE_TRIPLET_LOSS: False
  WORKERS: 0
  TRANS_SEP: False
  DEEPER_TRANSNET: True
  ONLINE_RENDERING: True
  RENDER_DIST: !!python/tuple [2.0]
  LIGHT_INT_MIN: 0.3
  LIGHT_INT_MAX: 3.0
  LIGHT_COLOR_VAR: 0.8
  LIGHT_R_MAX: 3.0
  LIGHT_R_MIN: 0.25
  TRANSNET_CAPACITY: !!python/tuple [10, 20, 32]
  SHIFT_MIN: -5.0
  SHIFT_MAX: 5.0
  SCALE_MIN: 0.975
  SCALE_MAX: 1.025
  OC_PROB: 0.3
  N_OCCLUDERS: 3
  TRUNC_PROB: 0.3
  TRUNC_X_MAX: 1.0
  TRUNC_Y_MAX: 1.0
  TRIPLET_LOSS_WT: 1.0
  ROI_CENTER_RANGE: [59.0, 69.0, 59.0, 69.0]
  ROI_SIZE_RANGE: [124.8, 131.2]
  USE_OCCLUSION: True